name: luvoria_chat
description: Chat application

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.5.2
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.3.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - .env
    - assets/
    - assets/appbg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/appicon.jpg"
    background_color: "#FFFFFF"
    theme_color: "#FF4D8D"
